name: bemed

services:
  traefik:
    container_name: traefik
    env_file: .env
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./config/traefik/:/etc/traefik/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    environment:
      - ADMIN_PASSWORD=admin
    ports:
      - "9000:9000" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 
      - "portainer_data:/data" 

  keycloak:
    container_name: keycloak
    env_file: .env
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:latest
    command:
      - "start-dev"
      - "--import-realm"
      # - "--override"
      # - "--optimized"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://db/${KC_DB_NAME}
      # - KC_PROXY_HEADERS=xforwarded
      # - KC_PROXY=edge
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      # - KC_TLS_HOSTNAME_VERIFIER=ANY
      # - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_LOG_CONSOLE_LEVEL=debug
    ports:
      - "8082:8080"
      - "8433:8443"
      - "8083:9000"
    volumes:
      - ./config/keycloak/:/opt/keycloak/data/import/:ro
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${DNS_PREFIX_KEYCLOAK}.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      # - "traefik.http.routers.keycloak.tls=true"

  db:
    container_name: database
    env_file: .env
    restart: unless-stopped
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./config/db/:/docker-entrypoint-initdb.d/:ro
      - database_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    env_file: .env
    restart: unless-stopped
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  backend:
    container_name: backend
    env_file: .env
    restart: unless-stopped
    build:
      context: ./backend
      target: production
    environment:
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_BACKEND_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    ports:
      - "3000:${BEMED_API_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${DNS_PREFIX_BEMED_BACKEND}.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=${BEMED_API_PORT}"
    depends_on:
      - keycloak
      - db

  frontend:
    container_name: frontend
    env_file: .env
    restart: unless-stopped
    build:
      context: ./frontend
      target: ${NODE_ENV}
      args:
        KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        KEYCLOAK_FRONTEND_CLIENT_ID: ${KEYCLOAK_FRONTEND_CLIENT_ID}
        KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
        BEMED_DOMAIN: ${BEMED_DOMAIN}
        DNS_PREFIX_KEYCLOAK: ${DNS_PREFIX_KEYCLOAK}
        DNS_PREFIX_BEMED_BACKEND: ${DNS_PREFIX_BEMED_BACKEND}
    environment:
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_FRONTEND_CLIENT_ID=${KEYCLOAK_FRONTEND_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - BEMED_DOMAIN=${BEMED_DOMAIN}
      - DNS_PREFIX_KEYCLOAK=${DNS_PREFIX_KEYCLOAK}
      - DNS_PREFIX_BEMED_BACKEND=${DNS_PREFIX_BEMED_BACKEND}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DNS_PREFIX_BEMED_FRONTEND}.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.root.rule=Host(`${BEMED_DOMAIN}`)"
      - "traefik.http.routers.root.entrypoints=web"
      - "traefik.http.routers.root.service=frontend"
volumes:
  database_data:
  portainer_data:
