version: "3.8"

name: bemed

services:
  keycloak:
    container_name: keycloak
    env_file: .env
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB_USERNAME=${MARIADB_USER}
      - KC_DB_PASSWORD=${MARIADB_PASSWORD}
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://db/${MARIADB_DATABASE}
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    ports:
      - "8180:8080"
    depends_on:
      - db

  db:
    container_name: database
    env_file: .env
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    env_file: .env
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db

  backend:
    container_name: backend
    env_file: .env
    build: 
      context: ./backend
      target: development
    environment:
      - KEYCLOAK_AUTH_URL=${KEYCLOAK_AUTH_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_BACKEND_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - keycloak

  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: ./frontend
      target: development
    environment:
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_FRONTEND_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    ports:
      - "5173:5173"
      - "80:80"

volumes:
  database_data:
