
name: bemed

services:
  traefik:
    container_name: traefik
    env_file: .env
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/traefik/:/etc/traefik/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  keycloak:
    container_name: keycloak
    env_file: .env
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:latest
    command:
      - "start-dev"
      - "--import-realm"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://db/${KC_DB_NAME}
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    volumes:
      - ./config/keycloak/:/opt/keycloak/data/import/:ro
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${DNS_PREFIX_KEYCLOAK}.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

  db:
    container_name: database
    env_file: .env
    restart: unless-stopped
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./config/db/:/docker-entrypoint-initdb.d/:ro
      - database_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    env_file: .env
    restart: unless-stopped
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  backend:
    container_name: backend
    env_file: .env
    restart: unless-stopped
    build:
      context: ./backend
      target: ${NODE_ENV}
    environment:
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_BACKEND_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${DNS_PREFIX_BEMED_BACKEND}.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=${BEMED_API_PORT}"
    depends_on:
      - keycloak
      - db

  frontend:
    container_name: frontend
    env_file: .env
    restart: unless-stopped
    build:
      context: ./frontend
      target: ${NODE_ENV}
    environment:
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_FRONTEND_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DNS_PREFIX_BEMED_FRONTEND}.${BEMED_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.root.rule=Host(`${BEMED_DOMAIN}`)"
      - "traefik.http.routers.root.entrypoints=web"
      - "traefik.http.routers.root.service=frontend"
volumes:
  database_data:
