site_name: BEMED Documentation
site_description: Comprehensive documentation for the BEMED Zero Waste Management System
site_author: BEMED Team
copyright: Copyright &copy; 2025 BEMED

# Set docs_dir to the root docs directory instead of content
docs_dir: ../../docs

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo: assets/favicon.ico
  favicon: assets/favicon.ico

nav:
  - Home: README.md
  - Backend API: backend-api.md
  - Frontend: frontend.md
  - Docker Services: docker-services.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - tables
  - admonition
  - footnotes

plugins:
  - search
