global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Change log level and format here ... [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
log:
  level: DEBUG

# --> (Optional) Enable accesslog here ...
# accesslog: {}
# <--

# Enable API and Dashboard here, don't do in production
# Defined in
api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    # http:
    #   middlewares:
    #     - xforwarded@file
  websecure:
    address: :443

http:
  middlewares:
    xforwarded:
      headers:
        customRequestHeaders:
          # Should be either "X-Forwarded-Proto: https" or "X-Forwarded-Proto: http"
          X-Forwarded-Proto: ${BEMED_PROTOCOL}
        customResponseHeaders:
          X-Forwarded-Proto: ${BEMED_PROTOCOL}

# Configure your CertificateResolver here...
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: ${ACME_EMAIL}
#       storage: "/letsencrypt/acme.json"
#       httpChallenge:
#         entryPoint: web

# --> (Optional) Disable TLS Cert verification check
# serversTransport:
#   insecureSkipVerify: true
# <--

providers:
  docker:
    exposedByDefault: false # <-- (Optional) Change this to true if you want to expose all services
    # Specify discovery network - This ensures correct name resolving and possible issues with containers, that are in multiple networks.
    # E.g. Database container in a separate network and a container in the frontend and database network.
    # network: frontend
  file:
    directory: /etc/traefik
    watch: true
